In [1]:
import datetime
from IPython.display import JSON
import pandas as pd
import requests

In [3]:
today = datetime.date.today()
tomorrow = str(today + datetime.timedelta(days=1))

In [2]:
cities = pd.read_csv('data/cities.csv')

In [ ]:
# def get_jsons(cities)

In [4]:

url = f"https://aerodatabox.p.rapidapi.com/flights/airports/icao/EDDB/{tomorrow}T00:00/{tomorrow}T11:59"

querystring = {"withLeg":"true","direction":"Arrival","withCancelled":"false","withCodeshared":"true","withCargo":"false","withPrivate":"false","withLocation":"false"}

headers = {
    'x-rapidapi-host': "aerodatabox.p.rapidapi.com",
    'x-rapidapi-key': "5816e969d8mshd4f781dd3077706p10311ajsn43dd0b10811c"
    }

response = requests.request("GET", url, headers=headers, params=querystring)

In [5]:
url = f"https://aerodatabox.p.rapidapi.com/flights/airports/icao/EDDB/{tomorrow}T12:00/{tomorrow}T23:59"

querystring = {"withLeg":"true","direction":"Arrival","withCancelled":"false","withCodeshared":"true","withCargo":"false","withPrivate":"false","withLocation":"false"}

headers = {
    'x-rapidapi-host': "aerodatabox.p.rapidapi.com",
    'x-rapidapi-key': "5816e969d8mshd4f781dd3077706p10311ajsn43dd0b10811c"
    }

response2 = requests.request("GET", url, headers=headers, params=querystring)

In [6]:
flights_json = response.json()
flights2_json = response2.json()
jsons= [flights_json,flights2_json]

In [9]:
dictionary = {"From":[],"Arrival (Local time)":[], "Arrival (UTC time)":[],"Terminal":[],"Airline":[],"Flight number":[],"Aircraft model":[]}
for j in jsons:
    for flight in j['arrivals']:
        try:
            dictionary["From"].append(flight['departure']["airport"]['name'])
        except:
            dictionary["From"].append("Unknown")
        try:
            dictionary["Arrival (Local time)"].append(flight['arrival']["scheduledTimeLocal"][10:-6])
        except:
            dictionary["Arrival (Local time)"].append("Unknown")
        try:
            dictionary["Arrival (UTC time)"].append(flight['arrival']["scheduledTimeUtc"][10:-1])
        except:
            dictionary["Arrival (UTC time)"].append("Unknown")
        try:
            dictionary["Terminal"].append(flight['arrival']["terminal"])
        except:
            dictionary["Terminal"].append("Unknown")
        try:
            dictionary["Airline"].append(flight['airline']["name"])
        except:
            dictionary["Airline"].append("Unknown")
        try:
            dictionary["Flight number"].append(flight['number'])
        except:
            dictionary["Flight number"].append("Unknown")
        try:
            dictionary["Aircraft model"].append(flight['aircraft']["model"])
        except:
            dictionary["Aircraft model"].append("Unknown")

In [10]:
flights = pd.DataFrame.from_dict(dictionary)

In [11]:
flights

,From,Arrival (Local time),Arrival (UTC time),Terminal,Airline,Flight number,Aircraft model
0,Riga,07:55,06:55,1,Air Baltic,BT 211,Airbus A220-300
1,Saarbrücken,08:10,07:10,0,Danish Air,DX 121,ATR 72
2,Munich,08:10,07:10,1,Lufthansa,LH 1928,Airbus A320 NEO
3,Luxembourg,08:15,07:15,1,Luxair,LG 9471,Bombardier Dash 8 Q400 / DHC-8-400
4,Pisa,08:45,07:45,Unknown,Ryanair,FR 9955,Boeing 737-800
...,...,...,...,...,...,...,...
175,Lisbon,22:50,21:50,1,TAP Air Portugal,TP 532,Airbus A319
176,Brussels,22:25,21:25,Unknown,Ryanair,FR 167,Boeing 737-800
177,Munich,22:55,21:55,1,Lufthansa,LH 1958,Airbus A321
178,Tenerife Island,22:25,21:25,1,easyJet,U2 5916,Airbus A320
179,Gran Canaria Island,22:30,21:30,Unknown,Ryanair,FR 2501,Boeing 737-800